#
#    ████████╗░█████╗░██╗░░██╗░█████╗░███████╗██████╗░░█████╗░
#    ╚══██╔══╝██╔══██╗╚██╗██╔╝██╔══██╗╚════██║╚════██╗██╔══██╗
#    ░░░██║░░░██║░░██║░╚███╔╝░╚█████╔╝░░░░██╔╝░░███╔═╝╚██████║
#    ░░░██║░░░██║░░██║░██╔██╗░██╔══██╗░░░██╔╝░██╔══╝░░░╚═══██║
#    ░░░██║░░░╚█████╔╝██╔╝╚██╗╚█████╔╝░░██╔╝░░███████╗░█████╔╝
#    ░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝░╚════╝░░░╚═╝░░░╚══════╝░╚════╝░
#
# список миров где трапку нельзя будет использовать
exclude-worlds:
  - spawn
# список регионов где трапку нельзя будет использовать
exclude-regions:
  - spawn

# настройка сообщений
messages:
  # сообщение если игрока не найдено
  player-offline: "&#C50000[❌] &#FF7979Игрок не в сети"
  # сообщение если выдать трапку с неправильный айди
  invalid-trap: "&#C50000[❌] &#FF7979Трапка &#FFE379{trap_id} &#FF7979не найдена"
  # сообщение если написать неверное число
  invalid-amount: "&#C50000[❌] &#FF7979Укажите корректное количество"
  # сообщение как правильно использовать команду
  usage: "&#06C500[✔] &#79FF7AИспользование: /vtrap give [ник] [id] [кол.]"

traps:
  trap1: # айди для трапки
    material: NETHERITE_SCRAP # материал
    name: "&#7F0606[&#830505★&#870505] &#900303Т&#940303р&#980202а&#9D0101п&#A10101к&#A50000а" # название трапки
    lore: # описание
      - ""
      - "&7Создает куб 3x3 блоков"
      - "&7Пропадает через время"
    schematic: "trap1.schem" # название схематики из папки schem
    duration: 15 # время жизни трапки (сколько она будет стоять)
    cooldown: 25 # задержка на использование трапки (в секундах)
    sound: BLOCK_PISTON_EXTEND # звук при спавне трапки
    despawn_sound: BLOCK_PISTON_EXTEND # звук когда трапка пропадает
    enchanted: false # будет ли предмет зачарован
    hide_enchants: true # скрывать ли зачар
    hide_attributes: true # скрывать ли атрибуты

  # ну и тут все тоже самое
  trap2:
    material: PRISMARINE_SHARD
    name: "&#138CB8[&#1289B5★&#1186B3] &#0E80ADВ&#0D7DABо&#0C7AA8д&#0B77A5н&#0A74A3а&#0871A0я &#066B9Aт&#056898р&#046595а&#026292п&#015F90к&#005C8Dа"
    lore:
      - ""
      - "&7Создает большой куб 7х7"
      - "&7В котором можно сражаться"
    schematic: "trap2.schem"
    duration: 20
    cooldown: 30
    sound: BLOCK_SLIME_BLOCK_PLACE
    despawn_sound: BLOCK_SLIME_BLOCK_PLACE
    enchanted: false
    hide_enchants: true
    hide_attributes: true