name: VTrap
version: '1.1'
main: ua.vdev.vtrap.VTrap
api-version: '1.16'
author: [ Tox_8729 ]
depend:
  - WorldEdit
  - WorldGuard

commands:
  vtrap:
    permission: vtrap.use

permissions:
  vtrap.use:
    default: op